import { IProjectBilling } from 'features/ProjectBilling/ProjectBillingModel';
import { IEodReportState } from 'features/EodReport/EodReportModel';
import { IClientState } from './IClientState';
import { IAppState } from './IAppState';
import { IAuthState } from './IAuthState';
import { IDeptState } from './IDeptState';
import { IProjectState } from './IProjectState';
import { IMarketPlaceAccountState } from './IMarketPlaceAccountState';
import { IConnectState } from './IConnectState';
import { IEmpProjectState } from './IEmpProjectsState';
import { IEmpState } from './IEmpState';
import { IEmpSalaryState } from './IEmpSalaryState';
import { IReportState } from './IReportsState';
import { IProjectDepartmentState } from './IProjectDept';
import { IConnectHistoryState } from './IConnectHistoryState';
import { IWeeklyBillingState } from './IWeeklyBillingState';
import { IWeeklyProjectState } from './IWeeklyProjectState';
import { ICapacityState } from './ICapacityState';
import { ILeaveState } from './ILeaveState';
import { IProjectHealthState } from './IProjectHealthState';
import { IMasterReportState } from './IMasterReport';
import { IDashBoardState } from './IDashBoardState';
import { ITeamLoggerState } from './ITeamLogger';
import { IPurchaseConnectsState } from './IPurchaseConnects';
import { IHRExpenseState } from './IHrExpenseState';
import { IExpenseCategoryState } from './IExpenseCategoryState';
import { IAssetsState } from './IAssetsState';
import { IAssetsCategoryState } from './IAssetsCategory';
import { IAssetsHandoverState } from './IAssetHandoveredState';
import { IHiringListState } from './IHiringListState';

type IRootState = {
  assets: IAssetsState;
  assetCategories: IAssetsCategoryState;
  assetHandovered: IAssetsHandoverState;
  app: IAppState;
  auth: IAuthState;
  dept: IDeptState;
  project: IProjectState;
  marketPlaceAccount: IMarketPlaceAccountState;
  client: IClientState;
  empProject: IEmpProjectState;
  connect: IConnectState;
  emp: IEmpState;
  empSalary: IEmpSalaryState;
  report: IReportState;
  projectBilling: IProjectBilling;
  projectHealth: IProjectHealthState;
  projectDept: IProjectDepartmentState;
  connectHistory: IConnectHistoryState;
  weeklyBilling: IWeeklyBillingState;
  weeklyProject: IWeeklyProjectState;
  capacity: ICapacityState;
  leaverReport: IMasterReportState;
  dashBoard: IDashBoardState;
  teame: ILeaveState;
  mastLogger: ITeamLoggerState;
  eodReport: IEodReportState;
  purchaseConnects: IPurchaseConnectsState;
  hrExpense: IHRExpenseState;
  leave: ILeaveState;
  teamLogger: ITeamLoggerState;
  masterReport: IMasterReportState;
  expenseCategory: IExpenseCategoryState;
  hiringlist: IHiringListState;
};

export default IRootState;
