# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"

      - name: Install Dependencies
        run: cd FrontEnd_New_Design;  npm install --f;

      - name: Create New Folder
        run: cd FrontEnd_New_Design; mkdir build

      - name: Build React App
        run: npm run build --if-present;
        env:
          CI: false
        working-directory: FrontEnd_New_Design\build

      - name: Copy artifacts
        run: |
          New-Item -ItemType Directory -Force -Path "C:/inetpub/crm-test"
          Copy-Item -Path "${{ github.workspace }}/FrontEnd_New_Design/build/*" -Destination "C:/inetpub/crm-test" -Recurse
        env:
          IIS_SERVER_HOST: ${{ secrets.IIS_HOST }}
          IIS_SERVER_USERNAME: ${{ secrets.IIS_USERNAME }}
          IIS_SERVER_PASSWORD: ${{ secrets.IIS_PASSWORD }}

      # - name: Deploy to IIS
      #   run: |
      #     Invoke-Expression -Command '.\deploy.ps1'
      #   env:
      #     IIS_SERVER_HOST: ${{ secrets.IIS_HOST }}
      #     IIS_SERVER_USERNAME: ${{ secrets.IIS_USERNAME }}
      #     IIS_SERVER_PASSWORD: ${{ secrets.IIS_PASSWORD }}
      #     working-directory: FrontEnd_New_Design\deploy.ps1

      # - name: Deploy
      #   run: |
      #     git config --global user.name $user_name
      #     git config --global user.email $user_email
      #     git remote set-url origin https://${github_token}@github.com/${repository}
      #     cd FrontEnd_New_Design; npm run deploy
      #     if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
      #   env:
      #     user_name: "github-actions[bot]"
      #     user_email: "github-actions[bot]@users.noreply.github.com"
      #     github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
      #     repository: ${{ github.repository }}

  # deploy:
  #   runs-on: windows-latest

  #   needs: build

  #   steps:
  #     - name: Deploy to IIS
  #       run: |
  #         $sourcePath = "FrontEnd_New_Design/build/*"
  #         $destinationPath = "C:/inetpub/crm-test"
  #         Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse -Force
  #       shell: pwsh

  # - name: Deploy to IIS
  #   uses: appleboy/scp-action@master
  #   with:
  #     host: ${{ secrets.IIS_HOST }}
  #     username: ${{ secrets.IIS_USERNAME }}
  #     password: ${{ secrets.IIS_PASSWORD }}
  #     local: "build/*"
  #     remote: "C:/inetpub/crm-test"
